apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync
  #generateName: pre-sync-
  annotations:
    argocd.argoproj.io/hook: PreSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: chamada
          image: curlimages/curl:8.10.1
          command: ["curl"]
          args:
            - -sS
            - --fail-with-body
            - -X
            - POST
            - -H
            - "Content-Type: application/json"
            - -d
            - '{"message": "Entrou em Pre Sync !!!"}'
            - https://webhook.site/2a980fe6-4eaf-4245-8060-a107c3198904
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync
  #generateName: sync-
  annotations:
    argocd.argoproj.io/hook: Sync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: chamada
          image: curlimages/curl:8.10.1
          command: ["curl"]
          args:
            - -sS
            - --fail-with-body
            - -X
            - POST
            - -H
            - "Content-Type: application/json"
            - -d
            - '{"message": "Entrou em Sync !!!"}'
            - https://webhook.site/2a980fe6-4eaf-4245-8060-a107c3198904
---
apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync
  #generateName: post-sync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: chamada
          image: curlimages/curl:8.10.1
          command: ["curl"]
          args:
            - -sS
            - --fail-with-body
            - -X
            - POST
            - -H
            - "Content-Type: application/json"
            - -d
            - '{"message": "Entrou em PostSync !!!"}'
            - https://webhook.site/2a980fe6-4eaf-4245-8060-a107c3198904
